name: Build artifacts

on:  
  push:
    tags:
      - '*.*.*'

  workflow_dispatch:

jobs:  
  build:
    runs-on: ubuntu-latest
    container: clojure:lein
    steps:
      - uses: actions/checkout@v4
      - name: install os deps
        run: |
          apt-get -qq update && apt-get -qy install rpm fakeroot
      - name: install lein deps
        run: |
          lein install
      - name: build packages
        run: |
          lein pkg
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            ./target/*.deb
            ./target/*.rpm
            ./target/*.md5
            ./target/*.jar
            ./target/*.bz2
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.release.tag_name }}
        with:
          name: artifacts
          draft: true
          files: ./target/*${{ github.event.release.tag_name }}*

  clojars:
    runs-on: ubuntu-latest
    container: clojure:lein
    if: ${{ github.event.release.tag_name }}
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: jlesquembre/clojars-publish-action@0.3
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}   

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: | 
            riemann/riemann:latest
            riemann/riemann:${{ github.event.release.tag_name }}
